--- #YAML:1.0
name:                Bio-Das
version:             1.06
abstract:            Client-side library for Distributed Genome Annotation System
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Bio::Root::Root:               0
    Compress::Zlib:                1
    HTML::Parser:                  3
    LWP:                           5
    MIME::Base64:                  2.12
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Lincoln Stein (lstein@cshl.edu)
